using System.Collections.Generic;
using Godot;
using Godot.Collections;

namespace PuzzlemakerPlus;

/// <summary>
/// Generates the extruded edges seen in corners.
/// </summary>
public static class EdgeModelGenerator
{
    /// <summary>
    /// Called every time a quad is generated from an edge.
    /// </summary>
    /// <param name="quad">The generated quad. The quad's normals will match the normal of the vertex it was generated from.</param>
    /// <remarks>Vert1 and Vert2 of the quad will always make up the edge it was generated from.</remarks>
    public delegate void EdgeQuadConsumer(Quad quad);

    /// <summary>
    /// Generate an edge model from a quad mesh.
    /// </summary>
    /// <param name="quadMesh">Quad mesh to generate from.</param>
    /// <param name="quadConsumer">Called every time a quad is generated.</param>
    /// <param name="minAngle">Minimum edge angle in radians.</param>
    /// <param name="MaxAngle">Maximum edge angle in radians.</param>
    /// <remarks>Edge extensions are based on the vertex normals of the first quad found. Call AverageNormals() first for proper results.
    /// Direction of the generated face is undefined; it should be rendered dual-sidedly.</remarks>
    public static void GenerateEdgeModel(
        SimpleQuadMesh quadMesh,
        EdgeQuadConsumer quadConsumer,
        float minAngle = Mathf.Pi / 4, // 45 degrees
        float MaxAngle = Mathf.Pi / 1.5f) // 120 degrees
    {
        quadMesh = new SimpleQuadMesh(quadMesh);
        foreach (var (edge, _) in quadMesh.GetEdgeRefsWithAngle(minAngle, MaxAngle))
        {
            // Only need to use the first ref

            var (vertRef1, vertRef2) = edge.GetVertices();

            Vector3 vert1 = quadMesh.GetVertex(vertRef1);
            Vector3 vert2 = quadMesh.GetVertex(vertRef2);

            Vector3 normal1 = -quadMesh.GetNormal(vertRef1);
            Vector3 normal2 = -quadMesh.GetNormal(vertRef2);

            Quad quad = new Quad(vert1, vert2, vert2 + normal2, vert1 + normal1);

            quad.Normal1 = normal1;
            quad.Normal2 = normal2;
            quad.Normal3 = normal2;
            quad.Normal4 = normal1;

            quadConsumer(quad);
        }
    }

    /// <summary>
    /// Build an edge model into a mesh containing the proper attributes for the shader.
    /// </summary>
    /// <param name="quads">Quads generated by <c>GenerateEdgeModel</c></param>
    /// <param name="mesh">Mesh to write to.</param>
    /// <returns><c>mesh</c></returns>
    /// <remarks>The normal of the closest vertex the quad was generated from goes in <c>custom0</c>,
    /// and the position of said vertex goes in <c>custom1</c>.</remarks>
    public static ArrayMesh BuildEdgeMesh(IEnumerable<Quad> quads, ArrayMesh mesh)
    {
        var builder = new MeshBuilder();
        foreach (var quad in quads)
        {
            builder.AddQuad(quad);
        }
        builder.ToMesh(mesh);
        return mesh;
        //List<Vector3> vertices = new();
        //List<Vector3> normals = new();
        //List<Vector3> custom0 = new();
        //List<Vector3> custom1 = new();
        //List<int> indices = new();

        //int numVerts = 0;

        //foreach (var quad in quads)
        //{
        //    Quad reset = quad.WithResetNormals();

        //    for (int i = 0; i < 4; i++)
        //    {
        //        vertices.Add(quad.GetVertex(i));
        //        normals.Add(reset.GetNormal(i));
        //        custom0.Add(quad.GetNormal(i));
        //    }

        //    custom1.Add(quad.Vert1);
        //    custom1.Add(quad.Vert2);
        //    custom1.Add(quad.Vert2);
        //    custom1.Add(quad.Vert1);

        //    indices.Add(numVerts + 0);
        //    indices.Add(numVerts + 1);
        //    indices.Add(numVerts + 2);

        //    indices.Add(numVerts + 0);
        //    indices.Add(numVerts + 2);
        //    indices.Add(numVerts + 3);

        //    numVerts += 4;
        //}

        ////Mesh.ArrayFormat format = Mesh.ArrayFormat.FormatVertex | Mesh.ArrayFormat.FormatNormal | Mesh.ArrayFormat.FormatIndex;
        ////format |= Mesh.ArrayFormat.FormatCustom0 | Mesh.ArrayFormat.FormatCustom1;

        ////format |= (Mesh.ArrayFormat)((int)Mesh.ArrayCustomFormat.RgbFloat << (int)Mesh.ArrayFormat.FormatCustom0Shift);
        ////format |= (Mesh.ArrayFormat)((int)Mesh.ArrayCustomFormat.RgbFloat << (int)Mesh.ArrayFormat.FormatCustom1Shift);

        //using (var gArray = new Array())
        //{
        //    gArray.Resize((int)Mesh.ArrayType.Max);
        //    gArray[(int)Mesh.ArrayType.Vertex] = vertices.ToArray();
        //    gArray[(int)Mesh.ArrayType.Normal] = normals.ToArray();
        //    gArray[(int)Mesh.ArrayType.Index] = indices.ToArray();
        //    //gArray[(int)Mesh.ArrayType.Custom0] = VectorExtensions.ToFloatArray(custom0.ToArray());
        //    //gArray[(int)Mesh.ArrayType.Custom1] = VectorExtensions.ToFloatArray(custom1.ToArray());

        //    mesh.AddSurfaceFromArrays(Mesh.PrimitiveType.Triangles, gArray);
        //}
        //return mesh;
    }
}
